version: "3"

services:
  app:
    networks:
      default:
        aliases:
          - devserver.local
    build: docker
    volumes:
      - .:/app

  database:
    image: mysql:5.7
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  redis:
    image: redis:5.0.1
